name: Deploy BlogAPIInfrastructure Stack to AWS

on:
  workflow_run:
    workflows: ["Deploy BlogGitHubStagingInfrastructure Stack to AWS"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-beta:
    runs-on: ubuntu-latest
    environment: beta
    permissions:
      id-token: write
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/BlogCDKGitHubOIDCDeployRole
          aws-region: us-east-1

      - name: Set Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download Synthesized Artifacts from S3
        run: |
          aws s3 cp --recursive s3://${{ secrets.CDK_STAGING_BUCKET_NAME }}/cdk-out/$COMMIT_HASH/ cdk.out/

      - name: Install CDK
        run: |
          npm install -g aws-cdk
          npm ci

      - name: Run CDK Diff for Beta
        run: cdk diff --app cdk.out BlogAPIInfrastructureBeta

      - name: Deploy API Stack to Beta
        run: |
          cdk deploy --app cdk.out BlogAPIInfrastructureBeta --require-approval never

  create-approval:
    steps:
      - name: Run CDK Diff for Prod
        run: cdk diff --app cdk.out BlogAPIInfrastructureProd | tee prod-diff.md

      - name: Attach CDK Diff to Prod Approval Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CDK_DEPLOY_TRIGGER }}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('prod-diff.md', 'utf8');
            const runId = process.env.GITHUB_RUN_ID;
            const repo = process.env.GITHUB_REPOSITORY;
            const workflowUrl = `https://github.com/${repo}/actions/runs/${runId}`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "🚀 Approve Production Deployment",
              body: `### CDK Diff for Production Deployment:\n\`\`\`\n${diff}\n\`\`\`\n\n[View Workflow & Approve Here](${workflowUrl})`,
              labels: ["approval-required"]
            });

  approve-prod:
    runs-on: ubuntu-latest
    needs: deploy-beta
    environment: prod
    steps:
      - name: Wait for manual approval
        run: echo "Waiting for manual approval in GitHub UI..."

# Enable prod after confirming approval workflow
#  deploy-prod:
#    runs-on: ubuntu-latest
#    needs: approve-prod
#    environment: prod
#    steps:
#      - name: Deploy API Stack to Prod
#        run: |
#          cdk deploy --app cdk.out BlogAPIInfrastructureProd --require-approval never