name: Deploy BlogGitHubStagingInfrastructure Stack to AWS

on:
  workflow_run:
    workflows: ["Synthesize CDK Stack"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download CDK Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cdk-artifacts
          path: cdk.out/
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/BlogCDKGitHubOIDCDeployRole
          aws-region: us-east-1

      - name: Deploy GitHub Infrastructure Stack
        run: |
          npm install -g aws-cdk
          npm ci
          cdk deploy BlogGitHubStagingInfrastructure --require-approval never
