name: Deploy BlogGitHubStagingInfrastructure Stack to AWS

on:
  workflow_run:
    workflows: ["Synthesize CDK Stack"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download CDK Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cdk-artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
